#!/bin/sh
git add git-commit .gitignore gitd Make.sh bin run run.urcd-curvecp run.urc2sd run.urc2sd-tor src README install-*.sh
TZ=UTC git commit --date="`date -u +'%s'`"
test -x /usr/lib/git-core/git-update-server-info && /usr/lib/git-core/git-update-server-info
