#!/bin/sh
git add -f \
 git-commit \
 .gitignore \
 gitd \
 Make.sh \
 bin \
 run \
 run.log \
 run.urcd-curvecp \
 run.urc2sd \
 run.urc2sd-tor \
 src \
 README \
 install-*.sh \
 db \
 contrib/ \
 DONATE

TZ=UTC git commit --date="`date -u +'%s'`"
test -x /usr/lib/git-core/git-update-server-info && /usr/lib/git-core/git-update-server-info
