#!/bin/sh
[ -z $3 ] && \
  echo $0' <addr> <port> </path/to/socket/>' 1>&2 && \
  exit 64

mkdir -p /services/urcd-tcplisten-"$1:$2" || exit 1

printf '#!/bin/sh -e\n' > \
  /services/urcd-tcplisten-"$1:$2"/run || exit 1

printf "exec tcpserver -H -R $1 $2 ./urcstream $3\n" >> \
  /services/urcd-tcplisten-"$1:$2"/run || exit 1

chmod +x /services/urcd-tcplisten-"$1:$2"/run || exit 1

test -L /services/urcd-tcplisten-"$1:$2"/urcstream || \
  ln -s `pwd`/urcstream /services/urcd-tcplisten-"$1:$2"/urcstream || \
  exit 1

test -L /service/urcd-tcplisten-"$1:$2" || \
  ln -s /services/urcd-tcplisten-"$1:$2" \
    /service/urcd-tcplisten-"$1:$2" || \
    exit 1
