#!/bin/sh -e
[ -z $2 ] && \
  echo $0' </path/to/sockets/> </path/to/hub/sockets>' 1>&2 && \
  exit 64

n=`ls /services | grep urcd-stream2hub | wc -l`

mkdir -p /services/urcd-stream2hub$n
mkdir -p /services/urcd-stream2hub$n/env

echo '0.0' > /services/urcd-stream2hub$n/env/LIMIT

echo '#!/bin/sh -e' > /services/urcd-stream2hub$n/run
echo "exec ./urcstream2hub $2 ./urcstream $1" >> /services/urcd-stream2hub$n/run
chmod +x /services/urcd-stream2hub$n/run

test -L /services/urcd-stream2hub$n/urcstream || \
  ln -s `pwd`/urcstream /services/urcd-stream2hub$n/urcstream

test -L /services/urcd-stream2hub$n/urcstream2hub || \
  ln -s `pwd`/urcstream2hub /services/urcd-stream2hub$n/urcstream2hub

test -L /service/urcd-stream2hub$n || \
  ln -s /services/urcd-stream2hub$n /service/urcd-stream2hub$n

sleep 4
svstat /service/urcd-stream2hub$n
